
LIBDIR=../lib
LIB=$(LIBDIR)/libParser.so

FLAG= -g -D__BOUCHON__ #-D__TST__
INCLUDE= -I../Tools/include  -I../SipsConfig/include
LIBS= ../lib/libTools.so ../lib/libConfig.so

include ../lib/common.mk

